* Code of Conduct for Loom

** Introduction
   This Code of Conduct outlines our expectations for all those who participate in our community, as well as the consequences for unacceptable behavior. We invite all those who participate in Loom to help us create safe and positive experiences for everyone.

** Our Standards
   In the spirit of fostering an open and welcoming environment, we commit to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation.

** Expected Behavior
   - Demonstrate empathy and kindness toward other people.
   - Be respectful of differing opinions, viewpoints, and experiences.
   - Give and gracefully accept constructive feedback.
   - Accept responsibility and apologize to those affected by our mistakes, and learn from the experience.
   - Focus on what is best not just for us as individuals, but for the overall community.

** Responsibilities
   - Following the [[./CONTRIBUTING.org][Contributing Guidelines]], especially regarding the Conventional Commit [[./style_guides/GIT_STYLE_GUIDE.org][strategy]], ensures clarity and consistency in project development.
   - Contributors should ensure their work adheres to the design and coding standards set forth in the project.
   - Maintainers are responsible for clarifying the standards of acceptable behavior and are expected to take appropriate and fair corrective action in response to any instances of unacceptable behavior.

** Unacceptable Behavior
   - The use of sexualized language or imagery, and unwelcome sexual attention or advances.
   - Trolling, insulting or derogatory comments, and personal or political attacks.
   - Public or private harassment.
   - Publishing others' private information, such as a physical or email address, without their explicit permission.
   - Other conduct which could reasonably be considered inappropriate in a professional setting.

** Enforcement
   - Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at [Contact Information]. All complaints will be reviewed and investigated promptly and fairly.
   - All community leaders are obligated to respect the privacy and security of the reporter of any incident.

** Attribution
   This Code of Conduct is adapted from the [[https://www.contributor-covenant.org][Contributor Covenant]], version 2.0, available [[https://www.contributor-covenant.org/version/2/0/code_of_conduct.html][here]].

Remember, a Code of Conduct not only sets expectations for participant behavior but also describes the procedures for handling unacceptable behavior. It's a key part of creating a safe and welcoming environment for all.
